-record(c0, {version :: non_neg_integer()}).
-record(c1, {time :: non_neg_integer(), random_bytes :: binary()}).
-record(c2, {time :: non_neg_integer(), time2 :: non_neg_integer(), random_echo :: binary()}).
